version: 2

sources:
  - name: airbnb
    schema: raw

    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4

      - name: hosts
        identifier: raw_hosts
        columns:
          - name: id
            tests:
              - not_null
              - unique  

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}
